### ISSUE TITLE
The setup page doesn't appear in Magento 2.1.3

### ISSUE THREAD

**Issue by ghost** [AltaPay/magento2#6]
It's possible to install the plugin, but the setup page doesn't show the Altapay option.

1. Go to: Stores > Configuration
2. Go to: Sales > Payment Methods
3. The setup page doesn't show the Altapay section
![01](https://cloud.githubusercontent.com/assets/20107467/21717437/237dd5fc-d411-11e6-8775-3e73442eca06.png)

We can see that the module is installed and enabled.

![02](https://cloud.githubusercontent.com/assets/20107467/21717461/53264578-d411-11e6-9025-42dad137355d.png)

**Comment by lsv** [comment]
Have you cleared the cache, and also enabled via bin/magento ?

**Comment by ghost** [comment]
>Have you cleared the cache

Yes, I tried the 'Flush Magento Cache' and 'Flush Cache Storage' options. Also tried disabling all the caches, but nothing worked.

>and also enabled via bin/magento ?

Yes.

**Comment by lsv** [comment]
Confirmed - Though I have no idea why, and nothing in the logs.

So im properly for the moment not accepting magento2 version newer than 2.1.2

**Comment by lsv** [comment]
Fixed in 0fa396e7c89f639941d532968af57236ed49365d

**Comment by ghost** [comment]
Could you please create a new release with only this correction so I can test it ASAP?

**Comment by ghost** [comment]
The problem persists, even after adding the following line to the json file:

"magento/product-community-edition": "<=2.1.3"

**Comment by lsv** [comment]
My bad, it should not be <=

Should only be a <


Den 18-01-2017 kl. 14:34 skrev et-altapay-com:

**Comment by ghost** [comment]
Actually I changed from < to <=, but it didn't work in both ways.

**Comment by lsv** [comment]
The problem is that 2.1.3 (a minor version) changed everything about 
payment modules, and they just ignore modules created the old-fashioned 
way - It should have been atleast version 2.2 before they made such a 
drastic change, or actually 3.0 if they were following semver


Den 18-01-2017 kl. 14:34 skrev et-altapay-com:

**Comment by lsv** [comment]
And you are using the master and not one of the tagged version?

I have not tagged this version with any number yet


Den 18-01-2017 kl. 14:40 skrev et-altapay-com:

**Comment by ghost** [comment]
I created two versions, 0.0.9.1 and 0.0.9.2, just to test those json file modifications.

**Comment by ghost** [comment]
Apparently it's solved. I followed the instructions in the link below to correct it:

https://github.com/magento/magento2/issues/7891

**Comment by lsv** [comment]
Nice find!

Well, I would still say that Magento2 is in somekind of a early beta function, so many problems all over.
